# Generated by Django 2.0.9 on 2019-03-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20190309_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_type',
            field=models.CharField(default='normal', max_length=120),
            preserve_default=False,
        ),
    ]
