# Generated by Django 2.0.9 on 2019-03-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='delivery_type',
        ),
    ]
