# Generated by Django 2.0.5 on 2018-06-28 03:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180628_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='Small', max_length=5),
            preserve_default=False,
        ),
    ]
