# Generated by Django 2.0.5 on 2018-06-28 06:24

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
    ]
