# Generated by Django 2.0.5 on 2018-06-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20180629_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='prospect_type',
        ),
    ]
