# Generated by Django 2.0.5 on 2018-06-28 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=250)),
                ('lookAndTrend', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cartDesc', models.CharField(blank=True, max_length=120, null=True)),
                ('shortDesc', models.CharField(blank=True, max_length=250, null=True)),
                ('materialAndCare', models.TextField(blank=True, null=True)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=5)),
                ('fitting', models.TextField(blank=True, null=True)),
                ('longDesc', models.TextField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('image1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('image2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('image3', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('image4', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('image5', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('image6', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('live', models.BooleanField(default=False)),
                ('itemLimited', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_add', to=settings.AUTH_USER_MODEL)),
                ('brandID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_brand', to='items.Brand')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_color', to='items.Color')),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_country', to='items.Country')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='prospectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_prospect', to='items.Prospect'),
        ),
        migrations.AddField(
            model_name='category',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='items.ProductType'),
        ),
    ]
