# Generated by Django 2.0.5 on 2018-06-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-categoryName']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['-prospect']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='cartDesc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fitting',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemLimited',
        ),
        migrations.RemoveField(
            model_name='item',
            name='live',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longDesc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='materialAndCare',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shortDesc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_field',
        ),
    ]
