# Generated by Django 2.0.5 on 2018-06-28 03:43

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cartDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_color', to='items.Color'),
        ),
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='fitting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='image5',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='image6',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemLimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='materialAndCare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shortDesc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=items.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
