# Generated by Django 2.0.5 on 2018-06-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180628_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='thumb',
        ),
    ]
