# Generated by Django 2.0.5 on 2018-06-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='thumb',
            new_name='thumb_image',
        ),
    ]
