# Generated by Django 2.0.5 on 2018-06-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_category_prospect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='prospect_type',
        ),
    ]
