# Generated by Django 2.0.5 on 2018-06-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_category_prospect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='prospect_type',
        ),
        migrations.AddField(
            model_name='category',
            name='prospect_type',
            field=models.ManyToManyField(to='items.Prospect'),
        ),
    ]
