# Generated by Django 2.0.5 on 2018-06-30 00:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_category_prospect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(to='items.Color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('red', 'Red'), ('pink', 'Pink'), ('brown', 'Brown'), ('XL', 'Xtra Large'), ('XXL', 'Xtra Xtra Large')], max_length=21),
        ),
    ]
