# Generated by Django 2.0.5 on 2018-06-30 00:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20180630_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'pink'), (3, 'yellow'), (4, 'purple'), (5, 'pink'), (6, 'green'), (7, 'blue'), (8, 'red'), (9, 'brown')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXL', 'Xtra Xtra Large')], max_length=12),
        ),
    ]
