# Generated by Django 2.0.5 on 2018-06-30 02:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20180630_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'pink'), (3, 'yellow'), (4, 'purple'), (5, 'pink'), (6, 'green'), (7, 'blue'), (8, 'red'), (9, 'brown'), (10, 'black'), (11, 'purple'), (12, 'orange'), (13, 'gray')], max_length=27),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'Not Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXL', 'Xtra Xtra Large')], max_length=15),
        ),
    ]
