# Generated by Django 2.0.5 on 2018-07-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20180630_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_color', to='items.Color'),
        ),
    ]
