# Generated by Django 2.0.9 on 2019-06-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priceMinusDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
