# Generated by Django 2.0.9 on 2019-03-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190323_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
